# Generated by Django 4.0 on 2021-12-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zawodnik',
            name='belki',
            field=models.PositiveSmallIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=0),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='pas',
            field=models.CharField(choices=[('BI', 'BIAŁY'), ('NIE', 'NIEBIESKI'), ('PUR', 'PURPURA'), ('BR', 'BRĄZOWY'), ('CZ', 'CZARNY')], default='BIAŁY', max_length=20),
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='wiek',
            field=models.PositiveSmallIntegerField(default=18),
        ),
    ]
