# Generated by Django 4.0 on 2021-12-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_zawodnik_fotka_zawodnik_poczatek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzasadnienie', models.TextField(blank=True, default='')),
                ('ranking', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (6, '5'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=10)),
                ('zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.zawodnik')),
            ],
        ),
    ]
