# Generated by Django 4.0 on 2022-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_ocena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('tytul', models.CharField(default='', max_length=50)),
                ('tresc', models.TextField(default='')),
            ],
        ),
    ]
