# Generated by Django 4.0 on 2022-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0006_uzytkownik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='password2',
        ),
    ]
